### ISSUE TITLE
Improve HUD 

### ISSUE THREAD

**Issue by alexandernanberg** [pmndrs/racing-game#118]
**Is your feature request related to a problem? Please describe.**

I think the HUD could use some improvements. Currently it deviates from most other games with the minimap and speedometer placement. IMO the UX would be better if they were placed in the more common places.

**Describe the solution you'd like**

Move speedometer to bottom right and minimap to bottom left. E.g. something similar to;

Forza 

![image](https://user-images.githubusercontent.com/8997319/121781509-63d6dc80-cba5-11eb-8a30-e3cfa6afc9b7.png)

GTA

![image](https://user-images.githubusercontent.com/8997319/121781656-232b9300-cba6-11eb-9fe7-3ae088d56544.png)

NFS

![image](https://user-images.githubusercontent.com/8997319/121781718-67b72e80-cba6-11eb-88c0-7159bd72b7f7.png)

I could start looking at this if you agree it's a good idea.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Gusted** [comment]
Sounds like a good Idea. It will most likely overhaul the whole HUD as every element should be replaced to a new position and for the speedometer be flipped around.

**Comment by drcmda** [comment]
speedomenter should make also be a like the last example, a gauge

**Comment by bjornstar** [comment]
I think this is fixed in #123, if we have further refinements we can create new issues.
