### ISSUE TITLE
bug: boost activating when empty

### ISSUE THREAD

**Issue by njm222** [pmndrs/racing-game#159]
**Describe the bug**

Boost is activating when the boost bar is empty

**To Reproduce**

1. Empty the boost bar
2. Keep tapping boost
3. Camera shake & exhaust animation activated

**Expected behavior**

When boost is empty camera shake & exhaust animation should not be activated

**Comment by lortschi** [comment]
camera shake could be removed if nitro is empty, but the boost exhaust ani is is really short as usual with nitro. I would let coz in real life behaves as same way if you do not have fuel anymore got last short pulls from engine.
