### ISSUE TITLE
To infinity and beyond 🚀

### ISSUE THREAD

**Issue by andy3520** [pmndrs/racing-game#193]
**Describe the bug**
Got hit by the train, it drag me into the tunnel and I went to the moon with unlimited increasing speed.

**To Reproduce**

1. Go to the rail
2. Got hit by the train 

**Expected behavior**
Get me back to the earth 😂

**Screenshots**
### Video I'm flying to the moon https://streamable.com/50odbw
![image](https://user-images.githubusercontent.com/38342390/141461429-2148a3f6-3748-47ba-9c0c-581b0f7db2d3.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 95

**Comment by aditbharadwaj** [comment]
![image](https://user-images.githubusercontent.com/6751554/142430667-e73a38e1-b3bd-442c-b1b6-bb6af7962635.png)
as its related to this issue only , it happedn to me when i pressed drift button too much it drifted me to infinity
