### ISSUE TITLE
Vehicle configs panel

### ISSUE THREAD

**Issue by lortschi** [pmndrs/racing-game#36]
It would be nice to have a vehicle configs panel where the gamer can set e.q. suspension, car height / distance to ground, wheel dimension etc. All the global settings in the raycastVehicle library.

Here is an old Cannon example from Schteppe: http://schteppe.github.io/vehicle-editor/

**Comment by drcmda** [comment]
this would be great, i think it could be better as a game mechanic though, more like a pre step that lets you configure your car (type, color, suspension, etc).

**Comment by ManVTish** [comment]
Anyone here who could help me with solving issues, I mean I'm new to open source and I have no idea. I do have a background in coding though. Please help me to get started.

**Comment by njm222** [comment]
I really like this so I'm aiming to get it in today! :)

**Comment by bjornstar** [comment]
Vehicle Editor is now live :)
