### ISSUE TITLE
Camera Flip

### ISSUE THREAD

**Issue by jchailatte** [pmndrs/racing-game#48]
Camera flips after opening and closing the editor so it shows the view behind the car upside down. Resetting the scene does not fix the camera either. The only way to fix it that I've found so far is to hit reset then open the editor which I assume flips the flipped camera back to the proper orientation. 
![image](https://user-images.githubusercontent.com/34077842/120864441-0f968180-c541-11eb-889b-8771092621f8.png)

**Comment by njm222** [comment]
I believe this is resolved with #183
