### ISSUE TITLE
not allow person to leave the level

### ISSUE THREAD

**Issue by SaraVieira** [pmndrs/racing-game#6]
![image](https://user-images.githubusercontent.com/1051509/120245784-a4159100-c26e-11eb-86b9-480657772c4e.png)

**Comment by nksaraf** [comment]
I would love to try to help with this!

**Comment by stockHuman** [comment]
This is nominally fixed by the heightfield's steep inclines.

**Comment by nksaraf** [comment]
Maybe just to be safe we can add some invisible walls so people cant drive out by mistake

**Comment by njm222** [comment]
This should be handled with #5 but we can just add a cannon box around the track as well to be on the safer side

**Comment by wuharvey** [comment]
Hmm, can we just teleport back into level if position is outside?

**Comment by drcmda** [comment]
Have you managed to go outside?

**Comment by njm222** [comment]
Yes there are gaps near the start

**Comment by drcmda** [comment]
I was thinking about adding a layer specific to the height map to the blend file, it has some other problems for instance determining height by making a snap from above does not always go well, the cacti for instance.

**Comment by njm222** [comment]
Hmmm I'm not very experienced with blender, but my assumption is that we need at least 2 different _snapshots_ to fix those issues

**Comment by drcmda** [comment]
1024 currently. I think the resolution works, but when it makes a snapshot from above a cactus for instance will branch out, creating a weird artifact when really it should be a pole. I'm going to model a more accurate layer.

**Comment by njm222** [comment]
I think I see the issue, you are exporting to .png right? I think you need to export to something that uses _linear space_ without gamma correction. So something like .exr or .tiff

**Comment by drcmda** [comment]
what i mean is this 

<img width="911" alt="Screenshot 2021-06-08 at 09 12 14" src="https://user-images.githubusercontent.com/2223602/121139976-a3b26280-c839-11eb-865b-94c26bf607a1.png">

this is caused because from above a cactus looks like this

![Uploading Screenshot 2021-06-08 at 09.13.44.png…]()

**Comment by njm222** [comment]
resolved by #198

Heightmap could still be improved
