### ISSUE TITLE
Train collision

### ISSUE THREAD

**Issue by mishushakov** [pmndrs/racing-game#61]
there are collisions in the game, but you cannot collide with the train :(

**Comment by mishushakov** [comment]
maybe adopt GTA V ideas?

> Randomly generated trains cannot be destroyed. They will simply push or phase through any obstacle on the tracks, and will resist any explosions

taken from https://gta.fandom.com/wiki/Freight_Train

**Comment by drcmda** [comment]
this would be super easy to do but currently the track is scaled and that makes it harder. i'll fix it in blender and then it should be straight forward.
