### ISSUE TITLE
Minimap using double render

### ISSUE THREAD

**Issue by Gusted** [pmndrs/racing-game#67]
As having some more iteration about the performance and rendering of this game to be optimal I came along the Mini map which got quite heavy when enabled and showed this strange double `webGL render` looking into the code
https://github.com/pmndrs/racing-game/blob/7aa38d4f14620a6b35131b94b65c232140a84d63/src/ui/Minimap.js#L69-L77

I see that gl.render is being executed twice on different scene. Whereby 1 on the main scene which explains why it's being heavy and the other one which seems more reasonable for me the rendering of the mini map. 

Removing line 69 solves the performance issue but created this strange border 
![image](https://user-images.githubusercontent.com/25481501/120921968-067af100-c6b6-11eb-91a9-830ff09813d1.png)

This is where my lack of understanding with Three.js comes in as I don't see anything that is affecting to create this border. Otherwise it could just be called "A feature" :)

EDIT: It's most likely this border is "unrendered" portion of the virtualScene.

**Comment by drcmda** [comment]
oh, i think that must be an oversight @ekaradon it shouldn't have to render the scene at all. rendering only once into a texture is enough, all it needs to render from there on is a plane and a dot.

**Comment by drcmda** [comment]
and btw, yes, i noticed it got jerkier, i was wondering what that was. still was playable and the stats say 60fps but something was slightly off.

**Comment by drcmda** [comment]
ah, ok, i think i found the problem,

```jsx
useFrame(() => {
 ...
}, 1)
```

without the "1" it will double render. with it the render call is correct bc now it render the scene as it should, and then the minimap on top of it.

**Comment by Gusted** [comment]
> and btw, yes, i noticed it got jerkier, i was wondering what that was

I'd recommend the https://profiler.firefox.com/ It gives you a lot insight and see which function does what and also gives you an insight if your code is doing a lot of CPU time or the native code is doing a lot of CPU time.
Trough that I'd was able to find the the performance hit in startup and now this minimap.

**Comment by drcmda** [comment]
better on your end now @Gusted ?

**Comment by Gusted** [comment]
> better on your end now @Gusted ?

Not really, but now it seems like
```javascript
gl.render(scene, camera) // line 69 of the file
```
is having a harder time
![image](https://user-images.githubusercontent.com/25481501/120923283-3d083a00-c6bd-11eb-9d06-fa970d3e3018.png)

**Comment by drcmda** [comment]
what it does now is that it takes rendering into its own hands, r3f doesn't render any longer. so rendering the scene takes the same toll as always, and afterwards it renders two sprites on top.

before this commit the renderloop would:

1. render the full scene
2. render the full scene
3. render two sprites

**Comment by Gusted** [comment]
> what it does now is that it takes rendering into its own hands, r3f doesn't render any longer.

Ah that makes more sense as why Minimap is doing this big rendering. It should be good then.
