### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by Gusted** [pmndrs/racing-game#71]
Now everyone has their own taste about how to structure files, however at this moment I see 2 problems.

- First letter capitalized or not? I see certain files not being capitalized at this moment should they be capitalized or should the others files not being capitalized as first letter?
- File suffix, we are working here with JSX syntax however are naming the files as `.js` files, I think they should be renamed to the correct file extension -> `.jsx`

**Comment by drcmda** [comment]
i think its quite common. components captitalized, everything else lowercase. index.js. Minimap.js `<Minimap />`. as for jsx, i have never seen anyone use jsx before, didn't even know it existed. i think it's perfect as it is now, same as the default react startup https://codesandbox.io/s/elated-stonebraker-f7ci1 or cra

**Comment by Gusted** [comment]
Hmm okay

**Comment by drcmda** [comment]
btw i found this: https://reactjs.org/docs/faq-structure.html react ofc is unopinionated but these suggestions are what i see most people using.

**Comment by bjornstar** [comment]
> Now everyone has their own taste about how to structure files, however at this moment I see 2 problems.
> 
> * First letter capitalized or not? I see certain files not being capitalized at this moment should they be capitalized or should the others files not being capitalized as first letter?
> * File suffix, we are working here with JSX syntax however are naming the files as `.js` files, I think they should be renamed to the correct file extension -> `.jsx`

We already had an issue with filename capitalization because git does not pick up capitalization changes by default. Some filesystems are case insensitive and didn't have an issue, while others are case sensitive and the build broke. We can avoid problems with capitalization if we standardize on lowercase.

I also agree that `.jsx` is the appropriate file extension for files using the jsx syntax. It's nice that the default configuration of `create-react-app` just makes it work, but we can have better build performance if we specify which files need transpiliation from `jsx` to `js`.

**Comment by drcmda** [comment]
if we use jsx, then i think we could move to vite. craco + esbuild is faster than cra, but vite is up without any delay, 0.01ms, also fast refresh is instant. but i think it wants "jsx" which i thought is weird. @bjornstar @Gusted should we?

**Comment by Gusted** [comment]
> @bjornstar @Gusted should we?

I've heard of Vite and seen it a couple of times being used. It's more tooling thann CRA offers at this moment and seems like they already have a [template for react](https://github.com/vitejs/vite/tree/main/packages/create-app/template-react) however if we for some reason want's to switch to Ts in the future it's  better to do it now and use the [typescript react template](https://github.com/vitejs/vite/tree/main/packages/create-app/template-react).

Vite overall seems great no issues raised from me. Additionally we could covert this into a discussion, to get some more input.

**Comment by bjornstar** [comment]
I don't mind trying `vite`, using `create-react-app` is really slow and painful.
