### ISSUE TITLE
Error since last commit

### ISSUE THREAD

**Issue by Gusted** [pmndrs/racing-game#74]
Since commit: https://github.com/pmndrs/racing-game/commit/0281251002a951e12a9ef98ce1e9333da318947f 
I've been experiencing this error 
![image](https://user-images.githubusercontent.com/25481501/120968224-1d721f80-c758-11eb-9f83-eeadfc6fef9e.png)

**Comment by njm222** [comment]
I resolved it with #66 
However it might not be robust enough.. not sure that effect does

**Comment by drcmda** [comment]
the ? needs to travel one more to the left

**Comment by Gusted** [comment]
> the ? needs to travel one more to the left

Beyond that there seems to be more errors appearing. e.g. the next line on which level.current is also undefined.

**Comment by drcmda** [comment]
im fixing them this evening. some race conditions with the mini map and the audio interface from drei is bugged

**Comment by drcmda** [comment]
should be better now

**Comment by Gusted** [comment]
Yup! Error is gone along with the other stuff that I noticed.
