### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by Gusted** [pmndrs/racing-game#77]
Since commit: https://github.com/pmndrs/racing-game/commit/b604d2b1fb740a27aa457b87071294d628a264c1

I've been experince(firefox-only) a regression whereby the camera is heavily shaking.

Please ignore the happering/stuttering, this is due to Nvidia, ~~fuck you~~ propriety drivers on Linux with Firefox.
https://user-images.githubusercontent.com/25481501/121050841-72d61d00-c7a8-11eb-8fef-8dd672a362a0.mp4

**Comment by drcmda** [comment]
latest build as well? and firefox only? that is very strange. i need to install it ..

**Comment by drcmda** [comment]
my suspicion is that this is because of lerp(..., delta) and ff handling delta weird? i started to lerp the steering bc it was immediate before (press left/right and the wheel just "pops" into place). i was told that using delta in lerp is correct because of different device refresh rates but could you try 0.1 everywhere it says "delta" just to see if that's the issue?

**Comment by Gusted** [comment]
> latest build as well?

Yep!



> and firefox only?

yes... But after getting ungoogled chromium to force the same stuttering as firefox by adjusting the gpu flags I was hit by an even greater issue of the whole car seems to be clipping trough the ground - Better said the car was in the ground and trying to move around. But once this stuttering doesn't occur it works completely fine.



> i was told that using delta in lerp is correct because of different device refresh rates

The refresh rate of webgl or something related? Or the rAF function?



> 0.1 everywhere it says "delta" just to see if that's the issue?

Highly reduces the shaking/stuttering of the vehicle but physics are broken so could be just that but definitely a difference.

**Comment by drcmda** [comment]
i did push a fix to use-cannon today due to another perf refression i hope its not related
could you try the delta -> 0.1 "fix" can the previous use-cannon?

**Comment by drcmda** [comment]
so the update to use-cannon is messing it up. if you just change the version back, is it ok? not at my computer rn to check.

**Comment by Gusted** [comment]
>  if you just change the version back, is it ok?

![image](https://user-images.githubusercontent.com/25481501/121075497-c6eefa80-c7c4-11eb-97ef-a6a46147d57f.png)
Doing a `yarn install` and `yarn run dev` and nope. Same behavior so you can exclude those packages as faulty 😄.

**Comment by drcmda** [comment]
that's a relief. i try to debug against the race-condition pr you've outlined, must be in there.

**Comment by Gusted** [comment]
> i try to debug against the race-condition 

You mean this commit? https://github.com/pmndrs/racing-game/commit/b604d2b1fb740a27aa457b87071294d628a264c1
After that the commit the strange behavior is appearing the race conditions commit(https://github.com/pmndrs/racing-game/commit/b604d2b1fb740a27aa457b87071294d628a264c1) is good and doesn't cause this behavior.

**Comment by drcmda** [comment]
so i cant repro that crazy shaking behaviour just the occasional frameskip in ff (macos) which is bad enough. but i went back to a3fdf54 and i get the same lag so i think that's just how ff runs webgl.

**Comment by Gusted** [comment]
Ill try to be looking into it myself, this is probably going to take some hours and end up with 1 little chance to fix this as every weird bug does.

**Comment by njm222** [comment]
Yeah ff is quite bad with webgl

**Comment by Gusted** [comment]
> Yeah ff is quite bad with webgl

They had some good progress on Windows + Mac, but from what I've seen following the issue trackers around the webgl, Linux is a dead end with Nvidia, because they don't have certain functionality/extensions just for linux drivers. It's very limited case this one FF + Linux + Nvidia so shouldn't be that much troubling for general users.

**Comment by Gusted** [comment]
I'd fucked up some `about:config` stuff. To anyone coming to this issue, make sure to not have any debugging enabled about the GPU. It will slow you down and cause weird weird behavior.
