### ISSUE TITLE
ui: instructions / controls

### ISSUE THREAD

**Issue by njm222** [pmndrs/racing-game#8]

**Comment by kiliman** [comment]
Current Controls:

|key|command|
|--|-----------|
|⬆️ w| Forward |
|⬇️ s | Backward|
|⬅️ a | Left        |
|➡️ d| Right      |
|*space*| Brake     |
|r      | Reset     |

https://github.com/pmndrs/racing-game/blob/main/src/utils/store.js

**Comment by drcmda** [comment]
added them to the ui
